// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// StoreInterface is an autogenerated mock type for the StoreInterface type
type StoreInterface struct {
	mock.Mock
}

// UpdateAnalytics provides a mock function with given fields: dishID, restaurantID
func (_m *StoreInterface) UpdateAnalytics(dishID int, restaurantID int) error {
	ret := _m.Called(dishID, restaurantID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAnalytics")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int, int) error); ok {
		r0 = rf(dishID, restaurantID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateDishRating provides a mock function with given fields: dishID, restaurantID
func (_m *StoreInterface) UpdateDishRating(dishID int, restaurantID int) error {
	ret := _m.Called(dishID, restaurantID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDishRating")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int, int) error); ok {
		r0 = rf(dishID, restaurantID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewStoreInterface creates a new instance of StoreInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStoreInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *StoreInterface {
	mock := &StoreInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
