// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	domain "overcooked-simplified/analytics-svc/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// AnalyticsInterface is an autogenerated mock type for the AnalyticsInterface type
type AnalyticsInterface struct {
	mock.Mock
}

// AnalyticsForRestaurant provides a mock function with given fields: restaurantID, period
func (_m *AnalyticsInterface) AnalyticsForRestaurant(restaurantID int, period string) domain.AnalyticsResponse {
	ret := _m.Called(restaurantID, period)

	if len(ret) == 0 {
		panic("no return value specified for AnalyticsForRestaurant")
	}

	var r0 domain.AnalyticsResponse
	if rf, ok := ret.Get(0).(func(int, string) domain.AnalyticsResponse); ok {
		r0 = rf(restaurantID, period)
	} else {
		r0 = ret.Get(0).(domain.AnalyticsResponse)
	}

	return r0
}

// DishStats provides a mock function with given fields: restaurantID, dishID
func (_m *AnalyticsInterface) DishStats(restaurantID int, dishID int) (map[string]interface{}, error) {
	ret := _m.Called(restaurantID, dishID)

	if len(ret) == 0 {
		panic("no return value specified for DishStats")
	}

	var r0 map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(int, int) (map[string]interface{}, error)); ok {
		return rf(restaurantID, dishID)
	}
	if rf, ok := ret.Get(0).(func(int, int) map[string]interface{}); ok {
		r0 = rf(restaurantID, dishID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(int, int) error); ok {
		r1 = rf(restaurantID, dishID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GlobalDistribution provides a mock function with no fields
func (_m *AnalyticsInterface) GlobalDistribution() (map[string]int, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GlobalDistribution")
	}

	var r0 map[string]int
	var r1 error
	if rf, ok := ret.Get(0).(func() (map[string]int, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() map[string]int); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]int)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RatingDistribution provides a mock function with given fields: restaurantID
func (_m *AnalyticsInterface) RatingDistribution(restaurantID int) (map[string]int, error) {
	ret := _m.Called(restaurantID)

	if len(ret) == 0 {
		panic("no return value specified for RatingDistribution")
	}

	var r0 map[string]int
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (map[string]int, error)); ok {
		return rf(restaurantID)
	}
	if rf, ok := ret.Get(0).(func(int) map[string]int); ok {
		r0 = rf(restaurantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]int)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(restaurantID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TopAllTime provides a mock function with no fields
func (_m *AnalyticsInterface) TopAllTime() ([]domain.DishAnalytics, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for TopAllTime")
	}

	var r0 []domain.DishAnalytics
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]domain.DishAnalytics, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []domain.DishAnalytics); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.DishAnalytics)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TopDishes provides a mock function with given fields: restaurantID, limit
func (_m *AnalyticsInterface) TopDishes(restaurantID int, limit int) ([]domain.DishAnalytics, error) {
	ret := _m.Called(restaurantID, limit)

	if len(ret) == 0 {
		panic("no return value specified for TopDishes")
	}

	var r0 []domain.DishAnalytics
	var r1 error
	if rf, ok := ret.Get(0).(func(int, int) ([]domain.DishAnalytics, error)); ok {
		return rf(restaurantID, limit)
	}
	if rf, ok := ret.Get(0).(func(int, int) []domain.DishAnalytics); ok {
		r0 = rf(restaurantID, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.DishAnalytics)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int) error); ok {
		r1 = rf(restaurantID, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TopToday provides a mock function with no fields
func (_m *AnalyticsInterface) TopToday() ([]domain.DishAnalytics, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for TopToday")
	}

	var r0 []domain.DishAnalytics
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]domain.DishAnalytics, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []domain.DishAnalytics); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.DishAnalytics)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAnalyticsInterface creates a new instance of AnalyticsInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAnalyticsInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *AnalyticsInterface {
	mock := &AnalyticsInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
