// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	domain "overcooked-simplified/dish-svc/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// DishRepository is an autogenerated mock type for the DishRepository type
type DishRepository struct {
	mock.Mock
}

// CreateDish provides a mock function with given fields: dish
func (_m *DishRepository) CreateDish(dish *domain.Dish) error {
	ret := _m.Called(dish)

	if len(ret) == 0 {
		panic("no return value specified for CreateDish")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Dish) error); ok {
		r0 = rf(dish)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteDish provides a mock function with given fields: restaurantID, dishID
func (_m *DishRepository) DeleteDish(restaurantID int, dishID int) (int64, error) {
	ret := _m.Called(restaurantID, dishID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteDish")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(int, int) (int64, error)); ok {
		return rf(restaurantID, dishID)
	}
	if rf, ok := ret.Get(0).(func(int, int) int64); ok {
		r0 = rf(restaurantID, dishID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(int, int) error); ok {
		r1 = rf(restaurantID, dishID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDish provides a mock function with given fields: restaurantID, dishID
func (_m *DishRepository) GetDish(restaurantID int, dishID int) (*domain.Dish, error) {
	ret := _m.Called(restaurantID, dishID)

	if len(ret) == 0 {
		panic("no return value specified for GetDish")
	}

	var r0 *domain.Dish
	var r1 error
	if rf, ok := ret.Get(0).(func(int, int) (*domain.Dish, error)); ok {
		return rf(restaurantID, dishID)
	}
	if rf, ok := ret.Get(0).(func(int, int) *domain.Dish); ok {
		r0 = rf(restaurantID, dishID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Dish)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int) error); ok {
		r1 = rf(restaurantID, dishID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListDishes provides a mock function with given fields: restaurantID
func (_m *DishRepository) ListDishes(restaurantID int) ([]domain.Dish, error) {
	ret := _m.Called(restaurantID)

	if len(ret) == 0 {
		panic("no return value specified for ListDishes")
	}

	var r0 []domain.Dish
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]domain.Dish, error)); ok {
		return rf(restaurantID)
	}
	if rf, ok := ret.Get(0).(func(int) []domain.Dish); ok {
		r0 = rf(restaurantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Dish)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(restaurantID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateDish provides a mock function with given fields: dish
func (_m *DishRepository) UpdateDish(dish *domain.Dish) error {
	ret := _m.Called(dish)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDish")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Dish) error); ok {
		r0 = rf(dish)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateDishImage provides a mock function with given fields: restaurantID, dishID, imageURL
func (_m *DishRepository) UpdateDishImage(restaurantID int, dishID int, imageURL string) error {
	ret := _m.Called(restaurantID, dishID, imageURL)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDishImage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int, int, string) error); ok {
		r0 = rf(restaurantID, dishID, imageURL)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewDishRepository creates a new instance of DishRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDishRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *DishRepository {
	mock := &DishRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
