// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	domain "overcooked-simplified/dish-svc/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// DishServiceInterface is an autogenerated mock type for the DishServiceInterface type
type DishServiceInterface struct {
	mock.Mock
}

// Create provides a mock function with given fields: dish
func (_m *DishServiceInterface) Create(dish *domain.Dish) error {
	ret := _m.Called(dish)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Dish) error); ok {
		r0 = rf(dish)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: restaurantID, dishID
func (_m *DishServiceInterface) Delete(restaurantID int, dishID int) (int64, error) {
	ret := _m.Called(restaurantID, dishID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(int, int) (int64, error)); ok {
		return rf(restaurantID, dishID)
	}
	if rf, ok := ret.Get(0).(func(int, int) int64); ok {
		r0 = rf(restaurantID, dishID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(int, int) error); ok {
		r1 = rf(restaurantID, dishID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Get provides a mock function with given fields: restaurantID, dishID
func (_m *DishServiceInterface) Get(restaurantID int, dishID int) (*domain.Dish, error) {
	ret := _m.Called(restaurantID, dishID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *domain.Dish
	var r1 error
	if rf, ok := ret.Get(0).(func(int, int) (*domain.Dish, error)); ok {
		return rf(restaurantID, dishID)
	}
	if rf, ok := ret.Get(0).(func(int, int) *domain.Dish); ok {
		r0 = rf(restaurantID, dishID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Dish)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int) error); ok {
		r1 = rf(restaurantID, dishID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: restaurantID
func (_m *DishServiceInterface) List(restaurantID int) ([]domain.Dish, error) {
	ret := _m.Called(restaurantID)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []domain.Dish
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]domain.Dish, error)); ok {
		return rf(restaurantID)
	}
	if rf, ok := ret.Get(0).(func(int) []domain.Dish); ok {
		r0 = rf(restaurantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Dish)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(restaurantID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: dish
func (_m *DishServiceInterface) Update(dish *domain.Dish) error {
	ret := _m.Called(dish)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Dish) error); ok {
		r0 = rf(dish)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateImage provides a mock function with given fields: restaurantID, dishID, imageURL
func (_m *DishServiceInterface) UpdateImage(restaurantID int, dishID int, imageURL string) error {
	ret := _m.Called(restaurantID, dishID, imageURL)

	if len(ret) == 0 {
		panic("no return value specified for UpdateImage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int, int, string) error); ok {
		r0 = rf(restaurantID, dishID, imageURL)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewDishServiceInterface creates a new instance of DishServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDishServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *DishServiceInterface {
	mock := &DishServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
