// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	domain "overcooked-simplified/dish-svc/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// OrderRepository is an autogenerated mock type for the OrderRepository type
type OrderRepository struct {
	mock.Mock
}

// CreateOrder provides a mock function with given fields: order
func (_m *OrderRepository) CreateOrder(order *domain.Order) error {
	ret := _m.Called(order)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Order) error); ok {
		r0 = rf(order)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetOrder provides a mock function with given fields: orderID
func (_m *OrderRepository) GetOrder(orderID int) (*domain.Order, []domain.OrderItem, error) {
	ret := _m.Called(orderID)

	if len(ret) == 0 {
		panic("no return value specified for GetOrder")
	}

	var r0 *domain.Order
	var r1 []domain.OrderItem
	var r2 error
	if rf, ok := ret.Get(0).(func(int) (*domain.Order, []domain.OrderItem, error)); ok {
		return rf(orderID)
	}
	if rf, ok := ret.Get(0).(func(int) *domain.Order); ok {
		r0 = rf(orderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(int) []domain.OrderItem); ok {
		r1 = rf(orderID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]domain.OrderItem)
		}
	}

	if rf, ok := ret.Get(2).(func(int) error); ok {
		r2 = rf(orderID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetQRCode provides a mock function with given fields: orderID
func (_m *OrderRepository) GetQRCode(orderID int) ([]byte, error) {
	ret := _m.Called(orderID)

	if len(ret) == 0 {
		panic("no return value specified for GetQRCode")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]byte, error)); ok {
		return rf(orderID)
	}
	if rf, ok := ret.Get(0).(func(int) []byte); ok {
		r0 = rf(orderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(orderID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListOrders provides a mock function with no fields
func (_m *OrderRepository) ListOrders() ([]domain.Order, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ListOrders")
	}

	var r0 []domain.Order
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]domain.Order, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []domain.Order); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Order)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaveQRCode provides a mock function with given fields: orderID, qr
func (_m *OrderRepository) SaveQRCode(orderID int, qr []byte) error {
	ret := _m.Called(orderID, qr)

	if len(ret) == 0 {
		panic("no return value specified for SaveQRCode")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int, []byte) error); ok {
		r0 = rf(orderID, qr)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewOrderRepository creates a new instance of OrderRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderRepository {
	mock := &OrderRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
