// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	domain "overcooked-simplified/dish-svc/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// OrderServiceInterface is an autogenerated mock type for the OrderServiceInterface type
type OrderServiceInterface struct {
	mock.Mock
}

// Create provides a mock function with given fields: order
func (_m *OrderServiceInterface) Create(order *domain.Order) error {
	ret := _m.Called(order)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Order) error); ok {
		r0 = rf(order)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: orderID
func (_m *OrderServiceInterface) Get(orderID int) (*domain.Order, error) {
	ret := _m.Called(orderID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *domain.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*domain.Order, error)); ok {
		return rf(orderID)
	}
	if rf, ok := ret.Get(0).(func(int) *domain.Order); ok {
		r0 = rf(orderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(orderID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetQRCode provides a mock function with given fields: orderID
func (_m *OrderServiceInterface) GetQRCode(orderID int) ([]byte, error) {
	ret := _m.Called(orderID)

	if len(ret) == 0 {
		panic("no return value specified for GetQRCode")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]byte, error)); ok {
		return rf(orderID)
	}
	if rf, ok := ret.Get(0).(func(int) []byte); ok {
		r0 = rf(orderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(orderID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with no fields
func (_m *OrderServiceInterface) List() ([]domain.Order, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []domain.Order
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]domain.Order, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []domain.Order); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Order)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// QRLink provides a mock function with given fields: orderID
func (_m *OrderServiceInterface) QRLink(orderID int) string {
	ret := _m.Called(orderID)

	if len(ret) == 0 {
		panic("no return value specified for QRLink")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(int) string); ok {
		r0 = rf(orderID)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// SaveQRCode provides a mock function with given fields: orderID, qr
func (_m *OrderServiceInterface) SaveQRCode(orderID int, qr []byte) error {
	ret := _m.Called(orderID, qr)

	if len(ret) == 0 {
		panic("no return value specified for SaveQRCode")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int, []byte) error); ok {
		r0 = rf(orderID, qr)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewOrderServiceInterface creates a new instance of OrderServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderServiceInterface {
	mock := &OrderServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
