// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// QRGenerator is an autogenerated mock type for the QRGenerator type
type QRGenerator struct {
	mock.Mock
}

// Generate provides a mock function with given fields: orderID
func (_m *QRGenerator) Generate(orderID int) ([]byte, error) {
	ret := _m.Called(orderID)

	if len(ret) == 0 {
		panic("no return value specified for Generate")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]byte, error)); ok {
		return rf(orderID)
	}
	if rf, ok := ret.Get(0).(func(int) []byte); ok {
		r0 = rf(orderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(orderID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewQRGenerator creates a new instance of QRGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewQRGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *QRGenerator {
	mock := &QRGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
