// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	domain "overcooked-simplified/dish-svc/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// RestaurantServiceInterface is an autogenerated mock type for the RestaurantServiceInterface type
type RestaurantServiceInterface struct {
	mock.Mock
}

// Create provides a mock function with given fields: rest
func (_m *RestaurantServiceInterface) Create(rest *domain.Restaurant) error {
	ret := _m.Called(rest)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Restaurant) error); ok {
		r0 = rf(rest)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: id
func (_m *RestaurantServiceInterface) Delete(id int) (int64, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (int64, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) int64); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Get provides a mock function with given fields: id
func (_m *RestaurantServiceInterface) Get(id int) (*domain.Restaurant, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *domain.Restaurant
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*domain.Restaurant, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) *domain.Restaurant); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Restaurant)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with no fields
func (_m *RestaurantServiceInterface) List() ([]domain.Restaurant, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []domain.Restaurant
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]domain.Restaurant, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []domain.Restaurant); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Restaurant)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: rest
func (_m *RestaurantServiceInterface) Update(rest *domain.Restaurant) error {
	ret := _m.Called(rest)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Restaurant) error); ok {
		r0 = rf(rest)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateImage provides a mock function with given fields: id, imageURL
func (_m *RestaurantServiceInterface) UpdateImage(id int, imageURL string) error {
	ret := _m.Called(id, imageURL)

	if len(ret) == 0 {
		panic("no return value specified for UpdateImage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int, string) error); ok {
		r0 = rf(id, imageURL)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRestaurantServiceInterface creates a new instance of RestaurantServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRestaurantServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *RestaurantServiceInterface {
	mock := &RestaurantServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
