// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	domain "overcooked-simplified/dish-svc/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// RestaurantRepository is an autogenerated mock type for the RestaurantRepository type
type RestaurantRepository struct {
	mock.Mock
}

// CreateRestaurant provides a mock function with given fields: rest
func (_m *RestaurantRepository) CreateRestaurant(rest *domain.Restaurant) error {
	ret := _m.Called(rest)

	if len(ret) == 0 {
		panic("no return value specified for CreateRestaurant")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Restaurant) error); ok {
		r0 = rf(rest)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteRestaurant provides a mock function with given fields: id
func (_m *RestaurantRepository) DeleteRestaurant(id int) (int64, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRestaurant")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (int64, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) int64); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRestaurant provides a mock function with given fields: id
func (_m *RestaurantRepository) GetRestaurant(id int) (*domain.Restaurant, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetRestaurant")
	}

	var r0 *domain.Restaurant
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*domain.Restaurant, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) *domain.Restaurant); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Restaurant)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListRestaurants provides a mock function with no fields
func (_m *RestaurantRepository) ListRestaurants() ([]domain.Restaurant, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ListRestaurants")
	}

	var r0 []domain.Restaurant
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]domain.Restaurant, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []domain.Restaurant); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Restaurant)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateRestaurant provides a mock function with given fields: rest
func (_m *RestaurantRepository) UpdateRestaurant(rest *domain.Restaurant) error {
	ret := _m.Called(rest)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRestaurant")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Restaurant) error); ok {
		r0 = rf(rest)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateRestaurantImage provides a mock function with given fields: id, imageURL
func (_m *RestaurantRepository) UpdateRestaurantImage(id int, imageURL string) error {
	ret := _m.Called(id, imageURL)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRestaurantImage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int, string) error); ok {
		r0 = rf(id, imageURL)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRestaurantRepository creates a new instance of RestaurantRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRestaurantRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *RestaurantRepository {
	mock := &RestaurantRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
