// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	domain "overcooked-simplified/rate-svc/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// ReviewRepository is an autogenerated mock type for the ReviewRepository type
type ReviewRepository struct {
	mock.Mock
}

// GetExistingReviewID provides a mock function with given fields: dishID, orderID, restaurantID
func (_m *ReviewRepository) GetExistingReviewID(dishID int, orderID int, restaurantID int) (int, error) {
	ret := _m.Called(dishID, orderID, restaurantID)

	if len(ret) == 0 {
		panic("no return value specified for GetExistingReviewID")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(int, int, int) (int, error)); ok {
		return rf(dishID, orderID, restaurantID)
	}
	if rf, ok := ret.Get(0).(func(int, int, int) int); ok {
		r0 = rf(dishID, orderID, restaurantID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(int, int, int) error); ok {
		r1 = rf(dishID, orderID, restaurantID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InsertReview provides a mock function with given fields: review
func (_m *ReviewRepository) InsertReview(review *domain.Review) error {
	ret := _m.Called(review)

	if len(ret) == 0 {
		panic("no return value specified for InsertReview")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Review) error); ok {
		r0 = rf(review)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ListDishReviews provides a mock function with given fields: dishID, restaurantID
func (_m *ReviewRepository) ListDishReviews(dishID int, restaurantID int) ([]domain.Review, error) {
	ret := _m.Called(dishID, restaurantID)

	if len(ret) == 0 {
		panic("no return value specified for ListDishReviews")
	}

	var r0 []domain.Review
	var r1 error
	if rf, ok := ret.Get(0).(func(int, int) ([]domain.Review, error)); ok {
		return rf(dishID, restaurantID)
	}
	if rf, ok := ret.Get(0).(func(int, int) []domain.Review); ok {
		r0 = rf(dishID, restaurantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Review)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int) error); ok {
		r1 = rf(dishID, restaurantID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateReview provides a mock function with given fields: id, review
func (_m *ReviewRepository) UpdateReview(id int, review *domain.Review) error {
	ret := _m.Called(id, review)

	if len(ret) == 0 {
		panic("no return value specified for UpdateReview")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int, *domain.Review) error); ok {
		r0 = rf(id, review)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ValidateDishInOrder provides a mock function with given fields: dishID, orderID, restaurantID
func (_m *ReviewRepository) ValidateDishInOrder(dishID int, orderID int, restaurantID int) (bool, error) {
	ret := _m.Called(dishID, orderID, restaurantID)

	if len(ret) == 0 {
		panic("no return value specified for ValidateDishInOrder")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(int, int, int) (bool, error)); ok {
		return rf(dishID, orderID, restaurantID)
	}
	if rf, ok := ret.Get(0).(func(int, int, int) bool); ok {
		r0 = rf(dishID, orderID, restaurantID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(int, int, int) error); ok {
		r1 = rf(dishID, orderID, restaurantID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewReviewRepository creates a new instance of ReviewRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReviewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReviewRepository {
	mock := &ReviewRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
