// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "overcooked-simplified/rate-svc/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// ReviewPublisher is an autogenerated mock type for the ReviewPublisher type
type ReviewPublisher struct {
	mock.Mock
}

// PublishReview provides a mock function with given fields: ctx, msg
func (_m *ReviewPublisher) PublishReview(ctx context.Context, msg domain.KafkaMessage) error {
	ret := _m.Called(ctx, msg)

	if len(ret) == 0 {
		panic("no return value specified for PublishReview")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.KafkaMessage) error); ok {
		r0 = rf(ctx, msg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewReviewPublisher creates a new instance of ReviewPublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReviewPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReviewPublisher {
	mock := &ReviewPublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
