// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// ReviewCache is an autogenerated mock type for the ReviewCache type
type ReviewCache struct {
	mock.Mock
}

// Exists provides a mock function with given fields: ctx, key
func (_m *ReviewCache) Exists(ctx context.Context, key string) (bool, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReviewMarkerKey provides a mock function with given fields: dishID, orderID
func (_m *ReviewCache) ReviewMarkerKey(dishID int, orderID int) string {
	ret := _m.Called(dishID, orderID)

	if len(ret) == 0 {
		panic("no return value specified for ReviewMarkerKey")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(int, int) string); ok {
		r0 = rf(dishID, orderID)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// SetMarker provides a mock function with given fields: ctx, key
func (_m *ReviewCache) SetMarker(ctx context.Context, key string) error {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for SetMarker")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewReviewCache creates a new instance of ReviewCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReviewCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReviewCache {
	mock := &ReviewCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
