// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "overcooked-simplified/rate-svc/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// ReviewServiceInterface is an autogenerated mock type for the ReviewServiceInterface type
type ReviewServiceInterface struct {
	mock.Mock
}

// CreateOrUpdate provides a mock function with given fields: ctx, review
func (_m *ReviewServiceInterface) CreateOrUpdate(ctx context.Context, review *domain.Review) error {
	ret := _m.Called(ctx, review)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrUpdate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Review) error); ok {
		r0 = rf(ctx, review)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ListDishReviews provides a mock function with given fields: dishID, restaurantID
func (_m *ReviewServiceInterface) ListDishReviews(dishID int, restaurantID int) ([]domain.Review, error) {
	ret := _m.Called(dishID, restaurantID)

	if len(ret) == 0 {
		panic("no return value specified for ListDishReviews")
	}

	var r0 []domain.Review
	var r1 error
	if rf, ok := ret.Get(0).(func(int, int) ([]domain.Review, error)); ok {
		return rf(dishID, restaurantID)
	}
	if rf, ok := ret.Get(0).(func(int, int) []domain.Review); ok {
		r0 = rf(dishID, restaurantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Review)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int) error); ok {
		r1 = rf(dishID, restaurantID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewReviewServiceInterface creates a new instance of ReviewServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReviewServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReviewServiceInterface {
	mock := &ReviewServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
